### ISSUE TITLE
Fehlermeldung report quiz assign

### ISSUE THREAD

**Issue by dfb60060HSBO** [rwthanalytics/moodle-local_learning_analytics#1]
Hallo Herr Dondorf,
wir testen Ihr Plugin an der Hochschule Bochum. Im Dashboard führt der Aufruf Test & Aufgaben in einem Kurs zu folgender Fehlermeldung:

Fehler: Argument 1 passed to local_learning_analytics\local\outputs\table::fancynumbercellcolored() must be of the type float, null given, called in [dirroot]/local/learning_analytics/reports/quiz_assign/lareport_quiz_assign.php on line 81

Gruß
..Roland

**Comment by thomasdondorf** [comment]
Hallo Roland,

danke für den Hinweis. Der Bug war bereits aufgefallen und tritt in Quizzen oder Assignments auf, bei denen eine spezielle Form der Bewertung gewählt wurde (z.B. eine Bewertung mit nur einer Kategorie). Für Mitte Januar ist bereits eine Update geplant, das den Fehler beheben wird. Das Ticket hier schließe ich dann anschließend.

Viele Grüße und schöne Feiertage,
Thomas

**Comment by thomasdondorf** [comment]
@dfb60060HSBO Bug ist in der Version `v0.15.0` behoben. Danke nochmal fürs Melden!

Habt ihr das Plugin bei euch bereits im Einsatz oder ist es geplant? Gerne würde ich mich hierzu kurz mit dir austauschen. Ich würde mich freuen, wenn du dich meldest: `dondorf (ät) lfi.rwth-aachen.de`.

Viele Grüße,
Thomas
