### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Dmfama20** [rwthanalytics/moodle-local_learning_analytics#20]
Hi,
first of all thank you very much for this really helpful tool. However, I we are missing some features:
- A possibility to sort the output by moodle groups
- A possibility to reset the logstore when the course is reused.

Did you have already thought about adding some kind of features?
TIA!
Best,
Alex

**Comment by thomasdondorf** [comment]
Hi Alex,

- Sort the output by Moodle groups -> There are currently no plans to implement this in the future.
- Reset the logstore -> The logstore plugin adds the task "Log table cleanup" to the Moodle API. You can either schedule this to run automatically or instead choose to run this task manually when needed. Check out the "loglifetime" option in the logstore plugin for more information. Alternatively, you can also purge the database table (`logstore_lanalytics_log`).

Let me know if that helps you.

Best,
Thomas

**Comment by Dmfama20** [comment]
Hi Thomas,
thank you very much!
I think I will go the way via the table logstore_lanalytics_log in order to delete logs of single courses. 
Best,
Alex

**Comment by thomasdondorf** [comment]
Great. I'll close this issue. Feel free to reopen if you have problems.
