### ISSUE TITLE
BibTex: doesn't it ignore capitalization?

### ISSUE THREAD

**Issue by lucaboesch** [rwthanalytics/moodle-local_learning_analytics#23]
Dear @thomasdondorf if taken as-is like you present my BibTex parser (~BibTeX~ Biber 2.19) does write the words not in {} brackets in lower case.
So, I think, the correct BibTex should be:

```
@phdthesis{Dondorf:844544,
    author       = {Dondorf, Thomas}, 
    othercontributors = {Nacken, Heribert and Persike, Malte},
    title        = {{L}earning {Analytics} for {Moodle}: {Facilitating} the {Adoption} of {Data} {Privacy} {Friendly} {Learning}     school       = {Rheinisch-Westfälische Technische Hochschule Aachen},
    type         = {Dissertation},
    address      = {Aachen},
    publisher    = {RWTH Aachen University},
    reportid     = {RWTH-2022-04002},
    year         = {2022},
    doi          = {10.18154/RWTH-2022-04002},
    url          = {https://publications.rwth-aachen.de/record/844544},
}
```

if you want to aim at the result you're presenting as blueprint.

Just a guess.

Best,
Luca

**Comment by thomasdondorf** [comment]
Hi Luca!

Thanks for caring, but it should be fine. It's up to the person citing and the used citation style how capitalization should be handled. Some styles might use title casing and some don't.

I only put `Moodle` and the first letter in brackets as Moodle is a term and the first letter should always be capitalized.

See https://en.wikipedia.org/wiki/Title_case#Title_case_in_references for more information.

Best,
Thomas

**Comment by lucaboesch** [comment]
Thanks, @thomasdondorf. TIL.
