### ISSUE TITLE
Better alternative to hard-coded English-German titles of custom fields

### ISSUE THREAD

**Issue by mudrd8mz** [rwthanalytics/moodle-local_learning_analytics#3]
This is not great: https://github.com/rwthanalytics/moodle-local_learning_analytics/blob/d3ef834ec4ec61edd49cae648ab9c1af69396d0c/classes/settings.php#L31-L40

I understand the limitations of customfields. Yet, it is quite common practice that the fields are still created using the names takes out from the language pack. That way the strings can be translated in AMOS (e.g. into Czech) and then is a Czech installs the plugin, the custom fields are created using the Czech titles (or falling back to English ones if they are not translated yet).

This is not great for multi-language sites but I believe it is still lesser evil (and more common) than these hard-coded English-German titles.

**Comment by mudrd8mz** [comment]
(especially as sites may not have the multilang filter enabled, or there can be dozens of languages installed etc)

**Comment by thomasdondorf** [comment]
Thanks for your issue. That's a good point. We'll change this to use language strings.

**Comment by martignoni** [comment]
Any progress about this? Would be very useful indeed (see eg. this french discussion: https://moodle.org/mod/forum/discuss.php?d=429819).

**Comment by methotdaniel** [comment]
Hello,
Your plugin is really useful!
I translated it for our community in French.
But could you make the necessary changes to make it really multilingual?
Indeed, some terms are still displayed in English and German.
Like the settings in the courses or the link in the side menu.
We had to correct them manually in the plugin files.
So these changes will not survive future updates.
Thanks in advance for your help.

**Comment by thomasdondorf** [comment]
Thanks for the link. An update is planned for beginning of January to fix this issue.

**Comment by thomasdondorf** [comment]
A new update has just been released. The plugin ensures that the implementation is working for pages that use the `multilang` filter (as our university uses it).

That means when setting the status to `customfield`, it will set the values depending on whether `multilang` was activated:
- If `multilang` is activated: It will concatenate existing language strings for the value to provide the proper language string.
- If `multilang` is not activated: It will choose the language string of the main Moodle language (as defined in `get_config('core', 'lang')`)

In addition, administrators will find a link in the admin menu that takes them to the pages where the category and option can be manually renamed:
![image](https://user-images.githubusercontent.com/13748265/148065317-9f6164be-62dc-47c7-a8d0-91d3083b228f.png)

The update is now available in the Moodle plugin store.

**Comment by thomasdondorf** [comment]
There were also a few strings missing in the Moodle translation (#4). Feel free to take a look to help to complete the French translation: https://lang.moodle.org/local/amos/view.php?t=1641552250&v=l&l=fr&c=local_learning_analytics&s&d

**Comment by martignoni** [comment]
> Feel free to take a look to help to complete the French translation

Done by @methotdaniel 🙇

**Comment by thomasdondorf** [comment]
Awesome, thanks a lot!
